#
# OpenTHC Full Docker Environment
#
# SPDX-License-Identifier: GPL-3.0-only
#


version: "3.7"
services:

  # The SQL Database Service
  sql:
    container_name: sql0
    image: openthc/sql:latest
    ports:
      - "127.0.0.1:42095:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

  # The Redis System
  redis:
    container_name: ram0
    image: redis

  # Compliance Reporting Engine
  cre:
    container_name: cre
    image: openthc/cre:latest
    ports:
      - "0.0.0.0:42010:80"
    depends_on:
      - sql
      - redis
    volumes:
      - type: bind
        source: ./etc/config-cre.php
        target: /opt/openthc/cre/etc/config.php
        read_only: true

  # Single Sign On / Auth
  sso:
    container_name: sso
    image: openthc/sso:latest
    ports:
      - "0.0.0.0:42020:80"
    depends_on:
      - sql
      - redis
    volumes:
      - type: bind
        source: ./etc/config-sso.php
        target: /opt/openthc/sso/etc/config.php
        read_only: true

  # Main Application / S2S / TNT
  app:
    container_name: app
    image: openthc/app:latest
    ports:
      - "0.0.0.0:42030:80"
    depends_on:
      - sql
      - redis
    volumes:
      - type: bind
        source: ./etc/config-app.php
        target: /opt/openthc/app/etc/config.php
        read_only: true
      - "./gfs:/opt/openthc/gfs"

  # Laboratory Interface
  lab:
    container_name: lab
    image: openthc/lab:latest
    ports:
      - "0.0.0.0:42040:80"
    depends_on:
      - sql
      - redis
    volumes:
      - type: bind
        source: ./etc/config-lab.php
        target: /opt/openthc/lab/etc/config.php
        read_only: true
      - "./gfs:/opt/openthc/gfs"
      # - "/opt/openthc/lab/lib:/opt/openthc/lab/lib"
      # - "/opt/openthc/lab/view:/opt/openthc/lab/view"

  # Point of Sale
  pos:
    container_name: pos
    image: openthc/pos:latest
    ports:
      - "0.0.0.0:42050:80"
    depends_on:
      - sql
      - redis
    volumes:
      - "./etc/config-pos.php:/opt/openthc/pos/etc/config.php"
