#
# OpenTHC Full Docker Environment
#
# SPDX-License-Identifier: GPL-3.0-only
#

version: "3.7"

services:

  # @see https://dev.to/kittipat1413/deploying-your-container-with-https-using-traefik-as-a-reverse-proxy-1859
  # @see https://www.youtube.com/watch?v=naCHq6sMMI8
  traefik:
    container_name: hub.openthc.me
    image: "traefik:v2.11.0"
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # The SQL Database Service
  sql:
    container_name: sql.openthc.me
    image: openthc/sql
    environment:
      - POSTGRES_PASSWORD="passweed"
    # volumes:
    #   - /opt/openthc-docker/sql:/var/lib/postgres/data

  # The Redis System
  # @see https://github.com/nextcloud/all-in-one/discussions/1731
  rdb:
    container_name: rdb.openthc.me
    image: redis

  # OPA
  # https://community.traefik.io/t/port-is-missing/4422
  opa:
    container_name: opa.openthc.me
    image: "openpolicyagent/opa:0.64.1"
    command:
      - "run"
      - "--server"
      - "--v1-compatible"
      - "--disable-telemetry"
      - "--addr=:6000"
      - "--diagnostic-addr=:6001"
    networks:
      default:
        aliases:
          - opa.openthc.me
    expose:
      - "6000"

  # Single Sign On Services
  sso:
    container_name: sso.openthc.me
    image: openthc/sso
    labels:
      - "traefik.http.routers.sso.rule=Host(`sso.openthc.me`)"
    depends_on:
      - traefik
      - sql
      - rdb
    volumes:
      - type: bind
        source: ./etc/sso/config.php
        target: /opt/openthc/sso/etc/config.php
        read_only: true
    networks:
      default:
        aliases:
          - sso.openthc.me
    expose:
      - "80"

  # Compliance Reporting Engine
  cre:
    container_name: cre.openthc.me
    image: openthc/cre
    labels:
      - "traefik.http.routers.cre.rule=Host(`cre.openthc.me`)"
    depends_on:
      - traefik
      - sql
      - rdb
    volumes:
      - type: bind
        source: ./etc/cre/config.php
        target: /opt/openthc/cre/etc/config.php
        read_only: true
      # - openthc-gfs
    networks:
      default:
        aliases:
          - cre.openthc.me
    expose:
      - "80"

  # PIPE
  # pipe:
  #   container_name: pipe.openthc.me
  #   image: openthc/pipe
  #   ports:
  #     - "42022:80"
  #   volumes:
  #     - type: bind
  #       source: ./etc/config-pipe.php
  #       target: /opt/openthc/pipe/etc/config.php
  #       read_only: true

  # BONG
  # bong:
  #   container_name: bong.openthc.me
  #   image: openthc/bong:
  #   ports:
  #     - "42024:80"
  #   volumes:
  #     - type: bind
  #       source: ./etc/config-bong.php
  #       target: /opt/openthc/bong/etc/config.php
  #       read_only: true

  # Main Application / S2S / TNT
  app:
    container_name: app.openthc.me
    image: openthc/app
    labels:
      - "traefik.http.routers.app.rule=Host(`app.openthc.me`)"
    depends_on:
      - traefik
      - sql
      - rdb
    volumes:
      - type: bind
        source: ./etc/app/config.php
        target: /opt/openthc/app/etc/config.php
        read_only: true
    networks:
      default:
        aliases:
          - app.openthc.me
    expose:
      - "80"
  #   ports:
  #     - "42030:80"

  # Laboratory Interface
  lab:
    container_name: lab.openthc.me
    image: openthc/lab
    labels:
      - "traefik.http.routers.lab.rule=Host(`lab.openthc.me`)"
    depends_on:
      - traefik
      - sql
      - rdb
    volumes:
      - type: bind
        source: ./etc/lab/config.php
        target: /opt/openthc/lab/etc/config.php
        read_only: true
    networks:
      default:
        aliases:
          - lab.openthc.me
    expose:
      - "80"

  # Point of Sale
  pos:
    container_name: pos.openthc.me
    image: openthc/pos
    labels:
      - "traefik.http.routers.pos.rule=Host(`pos.openthc.me`)"
    depends_on:
      - traefik
      - sql
      - rdb
    volumes:
      - type: bind
        source: ./etc/pos/config.php
        target: /opt/openthc/pos/etc/config.php
        read_only: true
    networks:
      default:
        aliases:
          - pos.openthc.me
    expose:
      - "80"

volumes:
  gfs:
    name: openthc-gfs
