#
# OpenTHC Full Docker Environment
#
# SPDX-License-Identifier: GPL-3.0-only
#

version: "3.7"

services:

  traefik:
    container_name: hub.openthc.me
    image: "traefik:v2.11.0"
    command: --providers.docker=true
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # The SQL Database Service
  sql:
    container_name: sql.openthc.me
    image: openthc/sql
    environment:
      - POSTGRES_PASSWORD="passweed"
    # ports:
    #   - "127.0.0.1:42095:5432"

  # The Redis System
  ram:
    container_name: ram.openthc.me
    image: redis

  # OPA
  opa:
    container_name: opa.openthc.me
    image: "openpolicyagent/opa:0.62.1"
    command: run --server --v1-compatible --addr :8181 --disable-telemetry
    networks:
      default:
        aliases:
          - opa.openthc.me

  # Single Sign On Services
  sso:
    container_name: sso.openthc.me
    image: openthc/sso
    depends_on:
      - traefik
      - sql
      - ram
    networks:
      default:
        aliases:
          - sso.openthc.me
    expose:
      - "80"
    volumes:
      - type: bind
        source: ./etc/sso/config.php
        target: /opt/openthc/sso/etc/config.php
        read_only: true
    labels:
      - "traefik.http.routers.sso.rule=Host(`sso.openthc.me`)"

  # Compliance Reporting Engine
  cre:
    container_name: cre.openthc.me
    image: openthc/cre
    depends_on:
      - sql
      - ram
    networks:
      default:
        aliases:
          - cre.openthc.me
    expose:
      - "80"
    # ports:
    #   - "42020:80"
    volumes:
      - type: bind
        source: ./etc/cre/config.php
        target: /opt/openthc/cre/etc/config.php
        read_only: true
    labels:
      - "traefik.http.routers.cre.rule=Host(`cre.openthc.me`)"
      # - openthc-gfs

  # PIPE
  # pipe:
  #   container_name: pipe.openthc.me
  #   image: openthc/pipe
  #   ports:
  #     - "42022:80"
  #   volumes:
  #     - type: bind
  #       source: ./etc/config-pipe.php
  #       target: /opt/openthc/pipe/etc/config.php
  #       read_only: true

  # BONG
  # bong:
  #   container_name: bong.openthc.me
  #   image: openthc/bong:
  #   ports:
  #     - "42024:80"
  #   volumes:
  #     - type: bind
  #       source: ./etc/config-bong.php
  #       target: /opt/openthc/bong/etc/config.php
  #       read_only: true

  # Main Application / S2S / TNT
  app:
    container_name: app.openthc.me
    image: openthc/app
    depends_on:
      - sql
      - ram
    networks:
      default:
        aliases:
          - app.openthc.me
    expose:
      - "80"
  #   ports:
  #     - "42030:80"
    volumes:
      - type: bind
        source: ./etc/app/config.php
        target: /opt/openthc/app/etc/config.php
        read_only: true
    labels:
      - "traefik.http.routers.app.rule=Host(`app.openthc.me`)"

  # Laboratory Interface
  lab:
    container_name: lab.openthc.me
    image: openthc/lab
    depends_on:
      - sql
      - ram
    networks:
      default:
        aliases:
          - lab.openthc.me
    expose:
      - "80"
  #   ports:
  #     - "42040:80"
    volumes:
      - type: bind
        source: ./etc/lab/config.php
        target: /opt/openthc/lab/etc/config.php
        read_only: true
    labels:
      - "traefik.http.routers.lab.rule=Host(`lab.openthc.me`)"

  # Point of Sale
  pos:
    container_name: pos.openthc.me
    image: openthc/pos
    depends_on:
      - sql
      - ram
    networks:
      default:
        aliases:
          - pos.openthc.me
    expose:
      - "80"
    # ports:
    #   - "42050:80"
    volumes:
      - type: bind
        source: ./etc/pos/config.php
        target: /opt/openthc/pos/etc/config.php
        read_only: true
    labels:
      - "traefik.http.routers.pos.rule=Host(`pos.openthc.me`)"

volumes:
  gfs:
    name: openthc-gfs
