#
# OpenTHC Full Docker Environment
#
# SPDX-License-Identifier: GPL-3.0-only
#

version: "3.7"

services:

  # The SQL Database Service
  sql:
    container_name: openthc-suite-sql
    image: openthc/sql
    environment:
      - POSTGRES_PASSWORD="OpenTHC!420"
    # ports:
    #   - "127.0.0.1:42095:5432"

  # The Redis System
  redis:
    # want to be openthc-rdb
    container_name: ram0
    image: redis

  # Save room at 42000:42000 for a main/control/install type app?

  # Single Sign On Services
  sso:
    container_name: openthc-suite-sso
    image: openthc/sso
    depends_on:
      - sql
      - redis
    ports:
      - "42010:80"
    volumes:
      - type: bind
        source: ../etc/config-sso.php
        target: /opt/openthc/sso/etc/config.php
        read_only: true

  # Compliance Reporting Engine
  cre:
    container_name: openthc-suite-cre
    image: openthc/cre
    depends_on:
      - sql
      - redis
    ports:
      - "42020:80"
    volumes:
      - type: bind
        source: ../etc/config-cre.php
        target: /opt/openthc/cre/etc/config.php
        read_only: true
      # - openthc-gfs

  # PIPE
  # pipe:
  #   container_name: openthc-suite-pipe
  #   image: openthc/pipe
  #   ports:
  #     - "42022:80"
  #   volumes:
  #     - type: bind
  #       source: ../etc/config-pipe.php
  #       target: /opt/openthc/pipe/etc/config.php
  #       read_only: true

  # BONG
  # bong:
  #   container_name: openthc-suite-bong
  #   image: openthc/bong:
  #   ports:
  #     - "42024:80"
  #   volumes:
  #     - type: bind
  #       source: ../etc/config-bong.php
  #       target: /opt/openthc/bong/etc/config.php
  #       read_only: true

  # Main Application / S2S / TNT
  app:
    container_name: openthc-suite-app
    image: openthc/app
    depends_on:
      - sql
      - redis
    ports:
      - "42030:80"
    volumes:
      - type: bind
        source: ../etc/config-app.php
        target: /opt/openthc/app/etc/config.php
        read_only: true

  # Laboratory Interface
  lab:
    container_name: openthc-suite-lab
    image: openthc/lab
    depends_on:
      - sql
      - redis
    ports:
      - "42040:80"
    volumes:
      - type: bind
        source: ../etc/config-lab.php
        target: /opt/openthc/lab/etc/config.php
        read_only: true

  # Point of Sale
  pos:
    container_name: openthc-suite-pos
    image: openthc/pos
    depends_on:
      - sql
      - redis
    ports:
      - "42050:80"
    volumes:
      - type: bind
        source: ../etc/config-pos.php
        target: /opt/openthc/pos/etc/config.php
        read_only: true

volumes:
  gfs:
    name: openthc-gfs
