#
# OpenTHC Full Docker Environment
#
# SPDX-License-Identifier: GPL-3.0-only
#

version: "3.7"

services:

  # The SQL Database Service
  sql:
    container_name: sql.openthc.example
    image: openthc/sql
    environment:
      - POSTGRES_PASSWORD="OpenTHC!420"
    networks:
      openthc-subnet:
        ipv4_address: 10.4.20.250
    # ports:
    #   - "127.0.0.1:42095:5432"

  # The Redis System
  ram:
    # want to be openthc-rdb
    container_name: ram.openthc.example
    image: redis
    networks:
      openthc-subnet:
        ipv4_address: 10.4.20.240

  # Save room at 42000:42000 for a main/control/install type app?

  # Single Sign On Services
  sso:
    container_name: sso.openthc.example
    image: openthc/sso
    depends_on:
      - sql
      - redis
    networks:
      openthc-subnet:
        ipv4_address: 10.4.20.10
    ports:
      - "42010:80"
    volumes:
      - type: bind
        source: ../etc/config-sso.php
        target: /opt/openthc/sso/etc/config.php
        read_only: true

  # Compliance Reporting Engine
  cre:
    container_name: cre.openthc.example
    image: openthc/cre
    depends_on:
      - sql
      - redis
    networks:
      openthc-subnet:
        ipv4_address: 10.4.20.20
    ports:
      - "42020:80"
    volumes:
      - type: bind
        source: ../etc/config-cre.php
        target: /opt/openthc/cre/etc/config.php
        read_only: true
      # - openthc-gfs

  # PIPE
  # pipe:
  #   container_name: pipe.openthc.example
  #   image: openthc/pipe
  #   ports:
  #     - "42022:80"
  #   volumes:
  #     - type: bind
  #       source: ../etc/config-pipe.php
  #       target: /opt/openthc/pipe/etc/config.php
  #       read_only: true

  # BONG
  # bong:
  #   container_name: bong.openthc.example
  #   image: openthc/bong:
  #   ports:
  #     - "42024:80"
  #   volumes:
  #     - type: bind
  #       source: ../etc/config-bong.php
  #       target: /opt/openthc/bong/etc/config.php
  #       read_only: true

  # Main Application / S2S / TNT
  app:
    container_name: app.openthc.example
    image: openthc/app
    depends_on:
      - sql
      - redis
    networks:
      openthc-subnet:
        ipv4_address: 10.4.20.30
    ports:
      - "42030:80"
    volumes:
      - type: bind
        source: ../etc/config-app.php
        target: /opt/openthc/app/etc/config.php
        read_only: true

  # Laboratory Interface
  lab:
    container_name: lab.openthc.example
    image: openthc/lab
    depends_on:
      - sql
      - redis
    networks:
      openthc-subnet:
        ipv4_address: 10.4.20.40
    ports:
      - "42040:80"
    volumes:
      - type: bind
        source: ../etc/config-lab.php
        target: /opt/openthc/lab/etc/config.php
        read_only: true

  # Point of Sale
  pos:
    container_name: pos.openthc.example
    image: openthc/pos
    depends_on:
      - sql
      - redis
    networks:
      openthc-subnet:
        ipv4_address: 10.4.20.50
    ports:
      - "42050:80"
    volumes:
      - type: bind
        source: ../etc/config-pos.php
        target: /opt/openthc/pos/etc/config.php
        read_only: true

networks:
  openthc-subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.4.20.0/24
          gateway: 10.4.20.1

volumes:
  gfs:
    name: openthc-gfs
